from app import create_app
from app.services import audio_handler, db_initializer, hotspot_setup


EXPECTED_API_CALLS = {
    'POST /api/V1/upload/logs',
    'GET /api/audio_url/<int:message_id>',
    'GET /api/audio_url_file/<int:message_id>',
    'POST /api/auth/login',
    'POST /api/auth/logout',
    'GET /api/auth/verify',
    'GET /api/available-ports',
    'GET /api/branding',
    'PUT /api/branding',
    'POST /api/channel',
    'DELETE /api/channel/<int:channel_id>',
    'GET /api/channel/<int:channel_id>',
    'PUT /api/channel/<int:channel_id>',
    'GET /api/channel/<int:channel_id>/recordings',
    'GET /api/channel_by_message/<int:message_id>',
    'GET /api/channels',
    'GET /api/docs/<path:filename>',
    'POST /api/event',
    'GET /api/frequencies',
    'POST /api/frequencies',
    'DELETE /api/frequencies/<int:freq_id>',
    'PUT /api/frequencies/<int:freq_id>',
    'GET /api/gpio/history',
    'GET /api/gpio/led/enabled',
    'POST /api/gpio/led/enabled/<enabled>',
    'GET /api/gpio/led/gpio',
    'POST /api/gpio/led/gpio/<int:gpio>',
    'GET /api/gpio/led/mode',
    'POST /api/gpio/led/mode/<mode>',
    'GET /api/gpio/pattern',
    'POST /api/gpio/pattern/<pattern>',
    'GET /api/gpio/relays',
    'POST /api/gpio/relays',
    'DELETE /api/gpio/relays/<name>',
    'GET /api/gpio/relays/<name>',
    'POST /api/gpio/relays/<name>/<action>',
    'POST /api/gpio/relays/<name>/gpio/<int:gpio>',
    'GET /api/gpio/relays/<name>/normal_state',
    'POST /api/gpio/relays/<name>/normal_state/<normal_state>',
    'GET /api/gpio/state',
    'POST /api/gpio/state/<state>',
    'POST /api/gpio/stop',
    'GET /api/hallucinations',
    'POST /api/hallucinations',
    'DELETE /api/hallucinations/<int:hallucinations_id>',
    'GET /api/health/devices',
    'GET /api/health/devices/<mac>',
    'POST /api/health/purge',
    'GET /api/health/system',
    'POST /api/hotspot/start',
    'GET /api/hotspot/status',
    'POST /api/hotspot/stop',
    'GET /api/incident-reports',
    'POST /api/incident-reports',
    'DELETE /api/incident-reports/<report_id>',
    'PATCH /api/incident-reports/<report_id>',
    'POST /api/incident-reports/<report_id>',
    'GET /api/logs',
    'DELETE /api/logs/<log_type>',
    'GET /api/logs/<log_type>',
    'GET /api/logs/statistics',
    'POST /api/logs_clear',
    'GET /api/maintenance/history',
    'POST /api/maintenance/run',
    'GET /api/maintenance/settings',
    'PUT /api/maintenance/settings',
    'GET /api/maintenance/system-usage',
    'POST /api/mfa/disable',
    'POST /api/mfa/setup',
    'GET /api/mfa/status',
    'POST /api/mfa/verify-setup',
    'GET /api/notifications',
    'DELETE /api/notifications/<notification_id>',
    'POST /api/notifications/clear',
    'GET /api/pagination-preferences/<username>',
    'POST /api/pagination-preferences/<username>',
    'GET /api/ping',
    'GET /api/profiles',
    'POST /api/profiles',
    'DELETE /api/profiles/<profile_name>',
    'GET /api/profiles/<profile_name>',
    'PUT /api/profiles/<profile_name>',
    'GET /api/profiles/features',
    'POST /api/queue/kill/<filename>',
    'GET /api/queue/logs',
    'POST /api/queue/purge',
    'POST /api/queue/requeue/<filename>',
    'POST /api/queue/start',
    'GET /api/queue/status',
    'POST /api/queue/stop',
    'GET /api/radio/<int:scanner_id>/channel/<int:channel>',
    'POST /api/radio/<int:scanner_id>/channel/<int:channel>',
    'POST /api/radio/<int:scanner_id>/park',
    'POST /api/radio/<int:scanner_id>/set_backlight',
    'POST /api/radio/<int:scanner_id>/squelch',
    'POST /api/radio/<int:scanner_id>/volume',
    'PUT /api/radio/<scanner_id>',
    'POST /api/radio/clear',
    'POST /api/radio/init',
    'GET /api/radio/list',
    'POST /api/radio/reassign',
    'POST /api/radio/restore_ids',
    'POST /api/reboot',
    'GET /api/recorders/config',
    'PUT /api/recorders/config',
    'POST /api/recorders/config/read',
    'POST /api/recorders/config/reboot',
    'POST /api/recorders/config/write',
    'GET /api/recorders/devices',
    'DELETE /api/recorders/devices/<path:port>',
    'GET /api/recorders/firmware',
    'POST /api/recorders/firmware',
    'DELETE /api/recorders/firmware/<firmware_id>',
    'PUT /api/recorders/firmware/<firmware_id>',
    'POST /api/recorders/flash',
    'POST /api/recorders/flash/clear',
    'GET /api/recorders/flash/progress',
    'GET /api/recorders/logs',
    'PUT /api/recorders/monitor',
    'POST /api/recorders/monitor/autoconfig',
    'GET /api/recorders/monitor/messages',
    'POST /api/recorders/monitor/reset',
    'POST /api/recorders/monitor/send',
    'POST /api/recorders/monitor/send-by-mac',
    'GET /api/recorders/monitor/status',
    'GET /api/recorders/reboot-counts',
    'POST /api/recorders/reboot-counts/sync',
    'GET /api/recorders/reboot-history',
    'POST /api/recorders/refresh',
    'GET /api/recorders/serial-data',
    'GET /api/recorders/serial-data/error-logs',
    'GET /api/recorders/serial-ports',
    'GET /api/recorders/terminal/poll',
    'POST /api/recorders/terminal/reboot',
    'POST /api/recorders/terminal/send',
    'GET /api/recording/<int:recording_id>/history',
    'DELETE /api/recording/<int:recording_id>/history/<int:version_number>',
    'GET /api/recording/<int:recording_id>/history/<int:version_number>',
    'GET /api/recording/<int:recording_id>/history/<int:version_number>/audio',
    'POST /api/recording/<int:recording_id>/history/<int:version_number>/revert',
    'GET /api/recording_duration_calculate/<int:message_id>',
    'GET /api/recordings',
    'DELETE /api/recordings/<int:recording_id>',
    'GET /api/recordings/<path:filename>',
    'GET /api/recordings/calendar/days',
    'GET /api/recordings/calendar/hours',
    'GET /api/recordings/calendar/recordings',
    'GET /api/recordings/inbox',
    'GET /api/recordings/inbox/count',
    'GET /api/recordings/inbox/range',
    'GET /api/recordings_tag/<int:recording_id>/tags',
    'POST /api/recordings_tag/<int:recording_id>/tags',
    'DELETE /api/recordings_tag/<int:recording_id>/tags/<string:tag>',
    'POST /api/recordings_tag/batch/tags',
    'GET /api/release-notes',
    'GET /api/s3/backup/history',
    'POST /api/s3/backup/start',
    'GET /api/s3/backup/status',
    'POST /api/s3/backup/test-samba',
    'GET /api/s3/restore/channels',
    'GET /api/s3/restore/days',
    'POST /api/s3/restore/execute',
    'GET /api/s3/restore/list',
    'GET /api/s3/restore/months',
    'GET /api/s3/restore/years',
    'GET /api/settings',
    'PUT /api/settings',
    'POST /api/settings/keywords',
    'DELETE /api/settings/keywords/<keyword>',
    'POST /api/settings/restart-service',
    'GET /api/settings/summary/metrics',
    'GET /api/tags',
    'POST /api/tags',
    'DELETE /api/tags/<int:tag_id>',
    'PATCH /api/tags/<int:tag_id>',
    'PUT /api/tags/<int:tag_id>',
    'GET /api/time',
    'POST /api/transcribe',
    'POST /api/transcribe/<int:record_id>',
    'GET /api/transcribe_save/<int:message_id>',
    'POST /api/transcribe_save/<int:message_id>',
    'POST /api/truncate_recordings',
    'GET /api/uploads/<filename>/status',
    'POST /api/uploads/queue',
    'GET /api/usb-recorders',
    'POST /api/usb-recorders',
    'DELETE /api/usb-recorders/<int:device_id>',
    'GET /api/usb-recorders/<int:device_id>',
    'PUT /api/usb-recorders/<int:device_id>',
    'POST /api/usb-recorders/<int:device_id>/start',
    'POST /api/usb-recorders/<int:device_id>/stop',
    'GET /api/usb-recorders/devices',
    'GET /api/users',
    'POST /api/users',
    'DELETE /api/users/<email>',
    'GET /api/users/<email>',
    'PUT /api/users/<email>',
    'GET /api/users/<email>/devices',
    'DELETE /api/users/<email>/devices/<device_id>',
    'POST /api/users/<email>/mfa/disable',
    'POST /api/users/<email>/mfa/enable',
    'POST /api/users/<email>/mfa/enforce',
    'POST /api/users/<email>/mfa/reset',
    'GET /api/users/<email>/permissions',
    'GET /api/v1/api-keys',
    'POST /api/v1/api-keys',
    'DELETE /api/v1/api-keys/<key_id>',
    'POST /api/v1/audio/s3',
    'GET /api/v1/channel-visual-states',
    'GET /api/v1/channel-visual-states/<mac>',
    'GET /api/v1/channels/<mac_address>',
    'GET /api/v1/devices/<mac>/events',
    'GET /api/v1/devices/<mac>/logs/content',
    'GET /api/v1/devices/<mac>/logs/files',
    'GET /api/v1/events',
    'POST /api/v1/events',
    'GET /api/v1/firmware/check',
    'GET /api/v1/firmware/download/<firmware_id>/<filename>',
    'GET /api/v1/scopes',
    'POST /api/v1/settings',
    'GET /api/v1/settings/<mac_address>',
    'GET /api/v1/transcriptions',
    'POST /api/v1/upload/logs',
    'POST /api/v2/audio/s3',
    'POST /api/version/apply',
    'POST /api/version/rollback',
    'GET /api/version/status',
}


def _create_test_app(monkeypatch):
    monkeypatch.setattr(audio_handler, "get_audio_handler", lambda: None)
    monkeypatch.setattr(db_initializer, "initialize_settings_database", lambda: None)
    monkeypatch.setattr(
        hotspot_setup,
        "run_initial_hotspot_setup",
        lambda: {"success": True, "skipped": True},
    )
    return create_app()


def _registered_api_calls(monkeypatch):
    app = _create_test_app(monkeypatch)

    return {
        f"{method} {rule.rule}"
        for rule in app.url_map.iter_rules()
        if rule.rule.startswith("/api/")
        for method in rule.methods - {"HEAD", "OPTIONS"}
    }


def test_all_api_calls_are_registered(monkeypatch):
    assert _registered_api_calls(monkeypatch) == EXPECTED_API_CALLS


def test_api_calls_do_not_have_duplicate_api_prefixes(monkeypatch):
    assert not {
        call
        for call in _registered_api_calls(monkeypatch)
        if call.split(" ", 1)[1].startswith("/api/api/")
    }


def test_unknown_api_route_returns_not_found(monkeypatch):
    app = _create_test_app(monkeypatch)

    response = app.test_client().get("/api/definitely-not-a-route")

    assert response.status_code == 404
